### PR TITLE
WIP: Upgrade to aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by RJKeevil**
Saw that AWS sdk v1 is in maintenance mode now and will quite soon be unsupported (https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/) .  So i took the plunge and had a stab at doing this upgrade.

### CODE REVIEW

**Comment by RJKeevil** [comment]
I think loading AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID from environment vars isn't working currently.  I'm finding it pretty tough to debug this part so let me know if you spot anything.

**Comment by adranwit** [comment]
Thanks for update,

**Comment by RJKeevil** [comment]
I think AWS_SDK_LOAD_CONFIG relates to getting creds from the config file, not from env vars.  I set AWS_ACCESS_KEY_ID, AWS_REGION and AWS_SECRET_ACCESS_KEY, the current version works fine, but my branch gives an access denied.  So somehow i think im missing a loader for these.

**Comment by RJKeevil** [comment]
Ah found the cause, for me this runs now and everything my app uses from afs s3 seems to work. I think its ready for review?

**Comment by adranwit** [comment]
Thanks for contributing,

**Comment by RJKeevil** [comment]
@adranwit would it be possible to tag this as a release? I have been running this for a while now and all seems to work nicely. I want to reference this import in a readme and it would be nice not to have to point users at a specific commit!

**Pull request merged**
